name: Deploy React with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile-front  # Change if your Dockerfile is elsewhere
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pawslink:latest

  connect-vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn

      - name: Decode VPN client config
        run: echo "${{ secrets.VPN_CLIENT_CONFIG }}" | base64 --decode > sitst-client.ovpn

      - name: Decode VPN CA certificate
        run: echo "${{ secrets.VPN_CA_CERT }}" | base64 --decode > vpn-st_ca.crt

      - name: Connect to VPN
        run: sudo openvpn --config sitst-client.ovpn --ca vpn-st_ca.crt --daemon

      - name: Wait for VPN connection
        run: sleep 10

      - name: Check Docker status
        run: docker ps
